# Generated by Django 4.2.28 on 2026-02-17 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="نام دسته")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True, unique=True, verbose_name="اسلاگ"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                (
                    "icon",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="آیکون (emoji یا class)"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#00d4aa", max_length=7, verbose_name="رنگ"
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="ترتیب نمایش")),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "دسته\u200cبندی",
                "verbose_name_plural": "دسته\u200cبندی\u200cها",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Prompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True, unique=True, verbose_name="اسلاگ"
                    ),
                ),
                ("content", models.TextField(verbose_name="متن پرامت")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="توضیحات کوتاه"),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "مبتدی"),
                            ("intermediate", "متوسط"),
                            ("advanced", "پیشرفته"),
                        ],
                        default="beginner",
                        max_length=20,
                        verbose_name="سطح دشواری",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("fa", "فارسی"), ("en", "English"), ("both", "هر دو")],
                        default="fa",
                        max_length=10,
                        verbose_name="زبان",
                    ),
                ),
                (
                    "views_count",
                    models.IntegerField(default=0, verbose_name="تعداد بازدید"),
                ),
                (
                    "likes_count",
                    models.IntegerField(default=0, verbose_name="تعداد لایک"),
                ),
                (
                    "copies_count",
                    models.IntegerField(default=0, verbose_name="تعداد کپی"),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="ویژه"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="منتشر شده"),
                ),
                (
                    "is_premium",
                    models.BooleanField(default=False, verbose_name="پریمیوم"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی"),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاریخ انتشار"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prompts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="نویسنده",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prompts",
                        to="prompts.category",
                        verbose_name="دسته\u200cبندی",
                    ),
                ),
            ],
            options={
                "verbose_name": "پرامت",
                "verbose_name_plural": "پرامت\u200cها",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="نام تگ"),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True, unique=True, verbose_name="اسلاگ"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#7c5cff", max_length=7, verbose_name="رنگ"
                    ),
                ),
            ],
            options={
                "verbose_name": "تگ",
                "verbose_name_plural": "تگ\u200cها",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="نام زیردسته")),
                ("slug", models.SlugField(allow_unicode=True, verbose_name="اسلاگ")),
                ("order", models.IntegerField(default=0, verbose_name="ترتیب")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="prompts.category",
                        verbose_name="دسته اصلی",
                    ),
                ),
            ],
            options={
                "verbose_name": "زیردسته",
                "verbose_name_plural": "زیردسته\u200cها",
                "ordering": ["order", "name"],
                "unique_together": {("category", "slug")},
            },
        ),
        migrations.CreateModel(
            name="PromptExample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("input_text", models.TextField(verbose_name="ورودی نمونه")),
                ("output_text", models.TextField(verbose_name="خروجی نمونه")),
                ("order", models.IntegerField(default=0, verbose_name="ترتیب")),
                (
                    "prompt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="examples",
                        to="prompts.prompt",
                        verbose_name="پرامت",
                    ),
                ),
            ],
            options={
                "verbose_name": "مثال",
                "verbose_name_plural": "مثال\u200cها",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="PromptCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="نام مجموعه")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True, unique=True, verbose_name="اسلاگ"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="ویژه"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "prompts",
                    models.ManyToManyField(
                        related_name="collections",
                        to="prompts.prompt",
                        verbose_name="پرامت\u200cها",
                    ),
                ),
            ],
            options={
                "verbose_name": "مجموعه",
                "verbose_name_plural": "مجموعه\u200cها",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="prompt",
            name="subcategory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="prompts",
                to="prompts.subcategory",
                verbose_name="زیردسته",
            ),
        ),
        migrations.AddField(
            model_name="prompt",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="prompts",
                to="prompts.tag",
                verbose_name="تگ\u200cها",
            ),
        ),
        migrations.AddIndex(
            model_name="prompt",
            index=models.Index(
                fields=["-views_count"], name="prompts_pro_views_c_64c428_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prompt",
            index=models.Index(
                fields=["-created_at"], name="prompts_pro_created_d50e89_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prompt",
            index=models.Index(
                fields=["is_published", "is_featured"],
                name="prompts_pro_is_publ_134bde_idx",
            ),
        ),
    ]
